version: 2.1

orbs:
    node: circleci/node@4.7.0

jobs:
    build_node:
        parameters:
            node-version:
                type: string
        docker:
            - image: circleci/node:<< parameters.node-version >>
        working_directory: ~/repo
        steps:
            - checkout
            - node/install-packages:
                  include-branch-in-cache-key: false
            - run:
                  name: Running Tests
                  command: npm run ci

workflows:
    build:
        jobs:
            - build_node:
                  matrix:
                      parameters:
                          node-version:
                              - '10'
                              - '11'
                              - '12'
                              - '13'
                              - '14'
                              - '16'
